apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: jenkins-backendconfig
  namespace: jenkins
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 3
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /login
    port: 8080
    