jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"

  numExecutors: 0
  mode: NORMAL

  # nodes: []

  clouds:
    - kubernetes:
        name: "kubernetes"
        serverUrl: "https://kubernetes.default.svc.cluster.local"
        namespace: "jenkins"
        jenkinsUrl: "http://jenkins-service.jenkins.svc.cluster.local:8080"
        jenkinsTunnel: "jenkins-service.jenkins.svc.cluster.local:50000"
        containerCapStr: "10"
        maxRequestsPerHostStr: "32"
        templates:
          - name: "jnlp-agent"
            label: "k8s-agent"
            serviceAccount: "jenkins"
            yamlMergeStrategy: "override"
            containers:
              - name: "jnlp"
                image: "jenkins/inbound-agent:latest"
                ttyEnabled: true
                command: ""
                args: ""
                resourceRequestCpu: "100m"
                resourceRequestMemory: "256Mi"
                resourceLimitCpu: "500m"
                resourceLimitMemory: "512Mi"
              - name: "kaniko"
                label: "kaniko"
                # image: "gcr.io/kaniko-project/executor:latest"
                image: "gcr.io/kaniko-project/executor:debug"
                command: "cat"
                # image: "kaniko:1.0.0"
                # command: "/kaniko/executor"
                # args: "--dockerfile /home/jenkins/agent/Dockerfile --context /home/jenkins/agent --no-push"
                ttyEnabled: true
                resourceRequestCpu: "100m"
                resourceRequestMemory: "100Mi"
                resourceLimitCpu: "256m"
                resourceLimitMemory: "256Mi"
                privileged: false # Kaniko runs without privileged mode
                envVars:
                  - envVar:
                      key: "DOCKER_CONFIG"
                      value: "/kaniko/.docker"
            volumes:
              - emptyDirVolume:
                  mountPath: "/home/jenkins/agent"
              - configMapVolume:
                  mountPath: "/home/jenkins/agent"
                  configMapName: "dummy-dockerfile"
              - secretVolume:
                  mountPath: "/kaniko/.docker"
                  secretName: "ecr-docker-config"
            idleMinutes: 5
            instanceCap: 5

  slaveAgentPort: 50000

  securityRealm:
    github:
      githubWebUri: "https://github.com"
      githubApiUri: "https://api.github.com"
      clientID: "Ov23liGvjdBxX3Z7hBZg"
      clientSecret: "${GITHUB_OAUTH_CLIENT_SECRET}"   # Could be loaded via credentials or env vars
      oauthScopes:  "read:org,user:email"
  
  # Authorization strategy
  authorizationStrategy:
    globalMatrix:
       entries:
         - user: 
             name: krimeshshah
             permissions:
               - "Overall/Administer"
         - user: 
             name: builder
             permissions:
               - "Job/Build"
               - "Job/Read"
    # projectMatrix:
    #   entries:
    #   - user:
    #       name: "krimeshshah"  # Replace this with the GitHub username of the user
    #       permissions:
    #         - "Overall/Administer"
    #   - group:
    #       name: "orgname*teamname1"
    #       permissions:
    #       - "Overall/Administer"
    #   - group:
    #       name: "orgname*teamname2"
    #       permissions:          
    #       - "Job/Build"
    #       - "Job/Cancel"
    #       - "Job/Read"
    #       - "Overall/Read"          
    #       - "View/Read" 


unclassified:
  # Optional other global settings
  location:
    url: "https://jenkins-eks.ks.ukinfosec.info" # Required for the image to spinned up to access jenkins over internet
    # url:  "http://172.17.0.1:8080" # UnComment it when need to build image to test in localmachine
  globalLibraries:
    libraries:
      - name: "my-shared-library"
        defaultVersion: "develop" # Or a specific tag/commit hash
        implicit: false # Set to true to load implicitly in all pipelines, false to require @Library annotation
        allowVersionOverride: true
        includeInChangesets: true
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/krimeshshah/jenkins-casc-k8s.git"
                credentialsId: "github-pat"

jobs:
    - script: >
        job('seed-all-dsl-jobs') {
          description('Seed job to create/update all DSL jobs from dsljobs/*.groovy')
          label('k8s-agent')
          scm {
            git {
              remote {
                url('https://github.com/krimeshshah/jenkins-casc-k8s.git')
                credentials('github-pat')
              }
              branch('*/develop')
            }
          }
          triggers {
            scm('H/15 * * * *')  // optional: poll schedule to automatically detect new DSL files
          }
          steps {
            jobDsl {
              targets('dslJobs/**/*.groovy')
              removedJobAction('DELETE')      // optionally remove jobs when DSL definitions are removed
              removedViewAction('DELETE')
              sandbox(true)
            }
          }
        }

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: "github-pat"
              username: "krimeshshah"
              password: "${GITHUB_PAT}"
              description: "Krimeshshah personal access token"
          # - aws:
          #     id: "aws-ecr-creds"
          #     accessKey: "${AWS_ACCESS_KEY_ID}"
          #     secretKey: "${AWS_SECRET_ACCESS_KEY}"
          #     description: "AWS ECR Access"

security:
   queueItemAuthenticator:
     authenticators:
     - global:
        strategy: triggeringUsersAuthorizationStrategy

tool:
  git:
    installations:
      - name: git
        home: /usr/bin/git
